language: node_js
node_js:
  - "6.10"
install:
  - npm i -g yarn && yarn
before_script:
    - webpack
deploy:
  provider: pages
  local-dir: build
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master