language: node_js
node_js:
  - "6.10"
install:
  - npm install
script:
  # run build script specified in package.json
  #- npm run ci
  - webpack -p
  # call script for deploying of produced artifacts
  #- bash ./.travis-deploy.sh
deploy:
  provider: pages
  local-dir: build
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master